apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kad.fullname" . }}-config-worker
  labels:
    {{- include "kad.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-worker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: config-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kad.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: config-worker
    spec:
      serviceAccountName: {{ include "kad.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: git-clone-dir
          emptyDir: {}
        - name: config-volume
          configMap:
            name: capten-plugins-config
            items:
              - key: TEKTON_PLUGIN_CONFIG
                path: {{ .Values.configWorker.tektonPluginConfigFile }}
              - key: CROSSPLANE_PLUGIN_CONFIG
                path: {{ .Values.configWorker.crossplanePluginConfigFile }}
      containers:
        - name: {{ .Chart.Name }}-config-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.config_worker.repository }}:{{ .Values.image.config_worker.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: git-clone-dir
              mountPath: {{ .Values.configWorker.configWorkerGitCloneDir }}
            - name: config-volume
              mountPath: {{ .Values.configWorker.pluginConfigDir }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            - name: TEMPORAL_SERVICE_URL
              value: "{{ .Values.temporal.temporalServiceURL }}.{{ .Release.Namespace }}.svc.cluster.local:7233"
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: VAULT_ADDR
              value: {{ .Values.vault.address }}
            - name: GIT_CLONE_DIR
              value: {{ .Values.configWorker.configWorkerGitCloneDir }}
            - name: VAULT_ROLE
              value: {{ .Values.vault.role }}
            - name: CASSANDRA_SERVICE_URL
              value: "{{ .Values.cassandra.serviceURL }}"
            - name: CASSANDRA_KEYSPACE_NAME
              value: "{{ .Values.cassandra.keyspaceName }}"
            - name: CASSANDRA_TABLE_NAME
              value: "{{ .Values.cassandra.name }}"
            - name: TEKTON_PLUGIN_CONFIG_FILE
              value: "{{ .Values.configWorker.pluginConfigDir }}/{{ .Values.configWorker.tektonPluginConfigFile }}"
            - name: CROSSPLANE_PLUGIN_CONFIG_FILE
              value: "{{ .Values.configWorker.pluginConfigDir }}/{{ .Values.configWorker.crossplanePluginConfigFile }}"
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.cassandra.secretName }}"
                  key: "username"
            - name: CASSANDRA_PASSWORD
              #value: "{{ .Values.cassandra.password }}"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.cassandra.secretName }}"
                  key: "password"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
